# Generated by Django 4.0.4 on 2025-01-08 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='stock_quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='purchase_orders',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='restock_orders',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
