# Generated by Django 4.0.4 on 2025-01-09 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_products_stock_quantity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='counter_sales',
            options={'verbose_name_plural': 'counter_sales'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name_plural': 'products'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name_plural': 'profile'},
        ),
        migrations.AlterModelOptions(
            name='purchase_orders',
            options={'verbose_name_plural': 'purchase_orders'},
        ),
        migrations.AlterModelOptions(
            name='restock_orders',
            options={'verbose_name_plural': 'restock_orders'},
        ),
        migrations.AddField(
            model_name='products',
            name='product_code',
            field=models.IntegerField(default=111000, unique=True),
            preserve_default=False,
        ),
    ]
