# Generated by Django 4.0.4 on 2025-07-10 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_scheduledpricechanges_activation_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduledpricechanges',
            old_name='product',
            new_name='products',
        ),
    ]
