# Generated by Django 4.0.4 on 2025-07-10 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_product_scheduledpricechanges_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduledpricechanges',
            old_name='products',
            new_name='product',
        ),
    ]
