# Generated by Django 4.0.4 on 2025-07-14 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_products_scheduledpricechanges_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='total_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
