# Generated by Django 4.0.4 on 2025-02-05 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='counter_sales',
            old_name='date',
            new_name='sale_date',
        ),
        migrations.RemoveField(
            model_name='counter_sales',
            name='product',
        ),
        migrations.CreateModel(
            name='sale_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.products')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.counter_sales')),
            ],
        ),
    ]
