# Generated by Django 4.0.4 on 2025-02-11 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_date_counter_sales_sale_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale_items',
            options={'verbose_name_plural': 'sale_items'},
        ),
        migrations.AddField(
            model_name='counter_sales',
            name='amount_tendered',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='counter_sales',
            name='change',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='counter_sales',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
