# Generated by Django 4.0.4 on 2025-03-04 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_sale_items_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='low_stock_level',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
