# Generated by Django 4.0.4 on 2025-07-21 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_products_original_cost_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledpricechanges',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
