# Generated by Django 4.0.4 on 2025-03-17 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0009_alter_restock_orders_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='restock_delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivered_quantity', models.IntegerField()),
                ('delivery_status', models.CharField(max_length=20)),
                ('delivery_date', models.DateTimeField(auto_now_add=True)),
                ('supplier_name', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('restock_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.restock_orders')),
            ],
        ),
    ]
