# Generated by Django 4.0.4 on 2025-03-17 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_restock_delivery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restock_delivery',
            old_name='delivered_quantity',
            new_name='quantity_delivered',
        ),
        migrations.AddField(
            model_name='restock_delivery',
            name='expected_quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
